from pathlib import Path
import argparse
import json

import numpy as np
import pandas as pd
import torch
from sentence_transformers import SentenceTransformer


PROJECT_ROOT = Path(__file__).resolve().parents[2]
PROCESSED_V2_DIR = PROJECT_ROOT / "data" / "processed" / "v2"
EMB_V2_DIR = PROJECT_ROOT / "outputs" / "v2" / "embeddings"
EMB_V2_DIR.mkdir(parents=True, exist_ok=True)


# 命令行参数：控制输入 item 文本表、BGE 模型、设备、批大小和输出目录
def parse_args():
    parser = argparse.ArgumentParser(description="Encode V2 item_text into BGE embedding cache.")

    parser.add_argument("--input", type=str, default=str(PROCESSED_V2_DIR / "item_text_v2.csv"), help="Path to item_text_v2.csv generated by Step 2.1.")
    parser.add_argument("--out-dir", type=str, default=str(EMB_V2_DIR), help="Output directory for V2 item embedding cache.")
    parser.add_argument("--model-name", type=str, default="BAAI/bge-small-zh-v1.5", help="SentenceTransformer model name or local path.")
    parser.add_argument("--batch-size", type=int, default=64, help="Batch size for encoding.")
    parser.add_argument("--device", type=str, default="auto", choices=["auto", "cuda", "cpu"], help="Device for encoding.")
    parser.add_argument("--max-seq-length", type=int, default=256, help="Max sequence length for text encoder.")
    parser.add_argument("--normalize", action=argparse.BooleanOptionalAction, default=True, help="Normalize embeddings for cosine retrieval / contrastive training.")

    args = parser.parse_args()
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be positive.")
    if args.max_seq_length <= 0:
        raise ValueError("--max-seq-length must be positive.")
    return args


# 路径展示：配置文件中优先保存相对于项目根目录的路径，便于迁移项目
def format_path(path: Path) -> str:
    path = path.resolve()
    try:
        return str(path.relative_to(PROJECT_ROOT))
    except ValueError:
        return str(path)


# 设备选择：默认优先使用 CUDA，不可用时自动回退到 CPU
def get_device(device_arg: str) -> str:
    if device_arg == "auto":
        return "cuda" if torch.cuda.is_available() else "cpu"
    if device_arg == "cuda" and not torch.cuda.is_available():
        print("[WARN] CUDA requested but not available. Falling back to CPU.")
        return "cpu"
    return device_arg


# 输入读取：读取 item_text_v2.csv，并整理成 item_id、item_text、category_id 三列
def read_item_text(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Input file not found: {path}")

    df = pd.read_csv(path, encoding="utf-8-sig", lineterminator="\n", low_memory=False)

    required_cols = {"item_id", "item_text"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    keep_cols = ["item_id", "item_text"]
    if "category_id" in df.columns:
        keep_cols.append("category_id")

    df = df[keep_cols].copy()
    df["item_id"] = pd.to_numeric(df["item_id"], errors="raise").astype("int64")
    df["item_text"] = df["item_text"].fillna("").astype(str).str.strip()
    df.loc[df["item_text"] == "", "item_text"] = "无文本信息"

    if "category_id" not in df.columns:
        df["category_id"] = "unknown"
    df["category_id"] = df["category_id"].fillna("unknown").astype(str)

    before = len(df)
    df = df.drop_duplicates("item_id").copy()
    after = len(df)
    if before != after:
        print(f"[WARN] drop duplicated item_id rows: {before} -> {after}")

    df = df.sort_values("item_id").reset_index(drop=True)
    return df


# 模型加载：使用 sentence-transformers 封装的 BGE 文本编码器
def load_model(model_name: str, device: str, max_seq_length: int) -> SentenceTransformer:
    model = SentenceTransformer(model_name, device=device)
    model.max_seq_length = max_seq_length
    return model


# 文本编码：将每个 item_text 编码成一个稠密向量
def encode_texts(model: SentenceTransformer, texts: list[str], batch_size: int, normalize: bool) -> np.ndarray:
    embeddings = model.encode(
        texts,
        batch_size=batch_size,
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=normalize,
    )
    embeddings = embeddings.astype("float32")
    return np.ascontiguousarray(embeddings)


# 结果校验：确认 item_id 与 embedding 行数对齐，并检查非法数值
def check_embeddings(item_ids: np.ndarray, embeddings: np.ndarray, normalize: bool) -> None:
    print("=" * 80)
    print("[CHECK]")
    print("item_ids shape:", item_ids.shape)
    print("embeddings shape:", embeddings.shape)
    print("embedding dtype:", embeddings.dtype)
    print("has nan:", np.isnan(embeddings).any())
    print("has inf:", np.isinf(embeddings).any())

    if len(item_ids) != embeddings.shape[0]:
        raise ValueError("item_ids and embeddings row count mismatch.")
    if embeddings.ndim != 2:
        raise ValueError(f"Embeddings must be 2D, got shape {embeddings.shape}")
    if np.isnan(embeddings).any() or np.isinf(embeddings).any():
        raise ValueError("Embeddings contain NaN or Inf.")

    if normalize:
        norms = np.linalg.norm(embeddings, axis=1)
        print("norm min:", float(norms.min()))
        print("norm max:", float(norms.max()))
        print("norm mean:", float(norms.mean()))


# 输出保存：保存 V2 item embedding cache、item_id 映射、元数据和编码配置
def save_outputs(df: pd.DataFrame, item_ids: np.ndarray, embeddings: np.ndarray, args, device: str) -> None:
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    emb_path = out_dir / "item_text_embeddings.npy"
    ids_path = out_dir / "item_ids.npy"
    meta_path = out_dir / "item_text_embedding_meta.csv"
    config_path = out_dir / "embedding_config.json"

    np.save(emb_path, embeddings)
    np.save(ids_path, item_ids)

    meta = df[["item_id", "item_text", "category_id"]].copy()
    meta["text_length"] = meta["item_text"].str.len()
    meta.to_csv(meta_path, index=False, encoding="utf-8-sig")

    config = {
        "model_name": args.model_name,
        "input_path": format_path(Path(args.input)),
        "device": device,
        "batch_size": args.batch_size,
        "max_seq_length": args.max_seq_length,
        "normalize": args.normalize,
        "num_items": int(len(df)),
        "embedding_dim": int(embeddings.shape[1]),
        "embedding_dtype": str(embeddings.dtype),
        "embedding_path": format_path(emb_path),
        "item_ids_path": format_path(ids_path),
        "meta_path": format_path(meta_path),
        "note": "category_id is saved as metadata only and is not used as text encoder input.",
    }

    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config, f, ensure_ascii=False, indent=2)

    print("=" * 80)
    print("[SAVED]")
    print(f"embeddings: {emb_path}")
    print(f"item ids: {ids_path}")
    print(f"meta: {meta_path}")
    print(f"config: {config_path}")


def main():
    args = parse_args()

    input_path = Path(args.input)
    device = get_device(args.device)

    print("=" * 80)
    print("Encode V2 Item Text")
    print("=" * 80)
    print(f"[INFO] project root: {PROJECT_ROOT}")
    print(f"[INFO] input: {input_path}")
    print(f"[INFO] model: {args.model_name}")
    print(f"[INFO] device: {device}")
    print(f"[INFO] batch size: {args.batch_size}")
    print(f"[INFO] max seq length: {args.max_seq_length}")
    print(f"[INFO] normalize: {args.normalize}")

    df = read_item_text(input_path)
    item_ids = df["item_id"].to_numpy(dtype=np.int64)
    texts = df["item_text"].tolist()

    print("=" * 80)
    print("[DATA]")
    print(f"num items: {len(df)}")
    print("sample:")
    for i in range(min(3, len(df))):
        print("-" * 80)
        print("item_id:", int(item_ids[i]))
        print("category_id:", df.loc[i, "category_id"])
        print("item_text:", texts[i][:300])

    print("=" * 80)
    print("[MODEL LOADING]")
    model = load_model(args.model_name, device, args.max_seq_length)

    print("[ENCODING]")
    embeddings = encode_texts(model, texts, args.batch_size, args.normalize)

    check_embeddings(item_ids, embeddings, args.normalize)
    save_outputs(df, item_ids, embeddings, args, device)

    print("=" * 80)
    print("Encode V2 item_text done.")


if __name__ == "__main__":
    main()
